name: Terraform Destroy (S3 State)

on:
workflow_dispatch:

jobs:
terraform-destroy:
runs-on: ubuntu-latest

```
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init (Connect to S3 State)
    run: terraform init -reconfigure

  - name: Verify State (Debug - Optional)
    run: terraform state list

  - name: Create Destroy Plan
    run: terraform plan -destroy -out=destroy.tfplan

  - name: Apply Destroy Plan
    run: terraform apply -auto-approve destroy.tfplan
```
